#!/bin/bash
function tar_name() { echo 'bash-4.4.tar.gz'; }
function tar_dir() { echo 'bash-4.4'; }

function config_pkg() {
    ./configure --prefix=/tools --without-bash-malloc \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make test \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && ln -s bash /tools/bin/sh \
    && return 0 || return 1
}
