#!/bin/bash

function tar_name() { echo 'binutils-2.27.tar.bz2'; }
function tar_dir() { echo 'binutils-2.27'; }

function config_pkg() {
    ./configure \
        --prefix=/tools            \
        --with-sysroot=$LFS        \
        --with-lib-path=/tools/lib \
        --target=$LFS_TGT          \
        --disable-nls              \
        --disable-werror
    return $?
}

function build_pkg() {
    return 0
}

function check_pkg() {
    return 1

}

function install_pkg() {
    return 0

}

function binutils_cross() {

PACKAGE_NAME='binutils-2.27.tar.bz2'
FOLDER_NAME='binutils-2.27'

cd /tools/work
rm -rf binutils-2.27
tar -xf ../src/binutils-2.27.tar.bz2
cd binutils-2.27

    && make > /dev/null        \
    && mkdir /tools/lib && ln -s lib /tools/lib64 \
    && make install > /dev/null
}
