#!/bin/bash
function tar_name() { echo 'binutils-2.27.tar.bz2'; }
function tar_dir() { echo 'binutils-2.27'; }

function config_pkg() {
    ./configure \
        --prefix=/tools            \
        --with-sysroot=$LFS        \
        --with-lib-path=/tools/lib \
        --target=$LFS_TGT          \
        --disable-nls              \
        --disable-werror           \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    mkdir /tools/lib && ln -s lib /tools/lib64
    make install \
    && return 0 || return 1
}
