#!/bin/bash
function tar_name() { echo 'bison-3.0.4.tar.xz'; }
function tar_dir() { echo 'bison-3.0.4'; }

function config_pkg() {
    ./configure --prefix=/tools \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
