#!/bin/bash
function tar_name() { echo 'coreutils-8.26.tar.xz'; }
function tar_dir() { echo 'coreutils-8.26'; }

function config_pkg() {
    FORCE_UNSAFE_CONFIGURE=1 \
    ./configure \
        --prefix=/tools \
        --enable-install-program=hostname \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make RUN_EXPENSIVE_TESTS=yes check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
