#!/bin/bash
function tar_name() { echo 'dejagnu-1.6.tar.gz'; }
function tar_dir() { echo 'dejagnu-1.6'; }

function config_pkg() {
    ./configure --prefix=/tools \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 install \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    return 0
}
