#!/bin/bash
function tar_name() { echo 'gcc-6.3.0.tar.bz2'; }
function tar_dir() { echo 'gcc-6.3.0'; }

function config_pkg() {
    tar -xf $SRC_DIR/mpfr-3.1.5.tar.xz
    mv -v mpfr-3.1.5 mpfr
    tar -xf $SRC_DIR/gmp-6.1.2.tar.xz
    mv -v gmp-6.1.2 gmp
    tar -xf $SRC_DIR/mpc-1.0.3.tar.gz
    mv -v mpc-1.0.3 mpc

    cat gcc/limitx.h gcc/glimits.h gcc/limity.h > `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h

    for file in gcc/config/{linux,i386/linux{,64}}.h
    do
        cp -u $file{,.orig}
        sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' -e 's@/usr@/tools@g' $file.orig > $file
        echo '
        #undef STANDARD_STARTFILE_PREFIX_1
        #undef STANDARD_STARTFILE_PREFIX_2
        #define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
        #define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
        touch $file.orig
    done

    sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64

    mkdir build && cd build
    CC=$LFS_TGT-gcc                                    \
    CXX=$LFS_TGT-g++                                   \
    AR=$LFS_TGT-ar                                     \
    RANLIB=$LFS_TGT-ranlib                             \
    ../configure                                       \
        --prefix=/tools                                \
        --with-local-prefix=/tools                     \
        --with-native-system-header-dir=/tools/include \
        --enable-languages=c,c++                       \
        --disable-libstdcxx-pch                        \
        --disable-multilib                             \
        --disable-bootstrap                            \
        --disable-libgomp \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && ln -s gcc /tools/bin/cc \
    && return 0 || return 1
}
