#!/bin/bash
function tar_name() { echo 'glibc-2.25.tar.xz'; }
function tar_dir() { echo 'glibc-2.25'; }

function config_pkg() {
    patch --forward --strip=1 --input=$SRC_DIR/glibc-2.25-fhs-1.patch \
    && mkdir build \
    && cd build \
    && ../configure \
        --prefix=/tools                    \
        --host=$LFS_TGT                    \
        --build=$(../scripts/config.guess) \
        --enable-kernel=2.6.32             \
        --with-headers=/tools/include      \
        libc_cv_forced_unwind=yes          \
        libc_cv_c_cleanup=yes \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
