#!/bin/bash
function tar_name() { echo 'linux-4.9.9.tar.xz'; }
function tar_dir() { echo 'linux-4.9.9'; }

function config_pkg() {
    make mrproper \
    && return 0 || return 1
}

function make_pkg() {
    make INSTALL_HDR_PATH=dest -j8 headers_install \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    cp -r dest/include/* /tools/include \
    && return 0 || return 1
}
