#!/bin/bash
[ $# -lt 3 ] && {
    echo "使用方式: $(basename $0) <tarball路徑> <解壓目錄> <要產生的腳本名稱>"
    exit 1
}

echo "#!/bin/bash
[ \$(id -u) -eq 0 ] && {
    echo \"請不要使用 root 執行.\"
    exit 1
}

function build() {
cd /tools/work
rm -rf $2
tar -xf ../src/$1
cd $2

./configure \\
    > /dev/null \\
    && make > /dev/null \\
    && make install > /dev/null
}

time build" > $3

chown root:lfs $3
chmod g+x,o-r $3
