#!/bin/bash
function tar_name() { echo 'tar_name'; }
function tar_dir() { echo 'tar_dir'; }

function config_pkg() {
    sh Configure -des -Dprefix=/tools -Dlibs=-lm \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    cp perl cpan/podlators/scripts/pod2man /tools/bin \
    && mkdir -p /tools/lib/perl5/5.24.1 \
    && cp -R lib/* /tools/lib/perl5/5.24.1 \
    && return 0 || return 1
}
