#!/bin/bash
function tar_name() { echo 'xz-5.2.3.tar.xz'; }
function tar_dir() { echo 'xz-5.2.3'; }

function config_pkg() {
    ./configure --prefix=/tools \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}

[ $(id -u) -eq 0 ] && {
    echo "請不要使用 root 執行."
    exit 1
}
