#!/bin/bash
function tar_name() { echo 'acl-2.2.52.src.tar.gz'; }
function tar_dir() { echo 'acl-2.2.52'; }

function config_pkg() {
    sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in \
    && sed -i "s:| sed.*::g" test/{sbits-restore,cp,misc}.test \
    && sed -i -e "/TABS-1;/a if (x > (TABS-1)) x = (TABS-1);" libacl/__acl_to_any_text.c \
    && ./configure \
        --prefix=/usr \
        --disable-static \
        --libexecdir=/usr/lib \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install install-dev install-lib \
    && {
        chmod 755 /usr/lib/libacl.so
        mv v /usr/lib/libacl.so.* /lib
        ln -sf ../../lib/$(readlink /usr/lib/libacl.so) /usr/lib/libacl.so
    } \
    && return 0 || return 1
}
