#!/bin/bash
function tar_name() { echo 'bash-4.4.tar.gz'; }
function tar_dir() { echo 'bash-4.4'; }

function config_pkg() {
    patch --forward --strip=1 --input=$SRC_DIR/bash-4.4-upstream_fixes-1.patch \
    && ./configure \
        --prefix=/usr \
        --docdir=/usr/share/doc/bash-4.4 \
        --without-bash-malloc               \
        --with-installed-readline \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    chown -R nobody . \
    && su nobody -s /bin/bash -c "PATH=$PATH make tests" \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && mv -f /usr/bin/bash /bin \
    && return 0 || return 1
}
