#!/bin/bash
function tar_name() { echo 'bison-3.0.4.tar.xz'; }
function tar_dir() { echo 'bison-3.0.4'; }

function config_pkg() {
    ./configure \
        --prefix=/usr \
        --docdir=/usr/share/doc/bison-3.0.4 \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
