#!/bin/bash
function tar_name() { echo 'bzip2-1.0.6.tar.gz'; }
function tar_dir() { echo 'bzip2-1.0.6'; }

function config_pkg() {
    patch --forward --strip=1 --input=/tools/src/bzip2-1.0.6-install_docs-1.patch \
    && sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile \
    && sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile \
    && make clean \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make PREFIX=/usr install \
    && {
        cp -v bzip2-shared /bin/bzip2
        cp -av libbz2.so* /lib
        ln -sv ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
        rm -v /usr/bin/{bunzip2,bzcat,bzip2}
        ln -sv bzip2 /bin/bunzip2
        ln -sv bzip2 /bin/bzcat
    } \
    && return 0 || return 1
}
