#!/bin/bash
function tar_name() { echo 'diffutils-3.5.tar.xz'; }
function tar_dir() { echo 'diffutils-3.5'; }

function config_pkg() {
    sed -i 's:= @mkdir_p@:= /bin/mkdir -p:' po/Makefile.in.in \
    && ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
