#!/bin/bash
function tar_name() { echo 'eudev-3.2.1.tar.gz'; }
function tar_dir() { echo 'eudev-3.2.1'; }

function config_pkg() {
    sed -r -i 's|/usr(/bin/test)|\1|' test/udev-test.pl
    sed -i '/keyboard_lookup_key/d' src/udev/udev-builtin-keyboard.c
    echo "HAVE_BLKID=1
BLKID_LIBS=\"-lblkid\"
BLKID_CFLAGS=\"-I/tools/include\"" > config.cache
    ./configure                     \
            --prefix=/usr           \
            --bindir=/sbin          \
            --sbindir=/sbin         \
            --libdir=/usr/lib       \
            --sysconfdir=/etc       \
            --libexecdir=/lib       \
            --with-rootprefix=      \
            --with-rootlibdir=/lib  \
            --enable-manpages       \
            --disable-static        \
            --config-cache          \
    && return 0 || return 1
}

function make_pkg() {
    LIBRARY_PATH=/tools/lib make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    mkdir -p /lib/udev/rules.d
    mkdir -p /etc/udev/rules.d
    make LD_LIBRARY_PATH=/tools/lib check \
    && return 0 || return 1
}

function install_pkg() {
    make LD_LIBRARY_PATH=/tools/lib install \
    && {
        tar -xf $SRC_DIR/udev-lfs-20140408.tar.bz2
        make -f udev-lfs-20140408/Makefile.lfs install
    } \
    && return 0 || return 1
}
