#!/bin/bash
function tar_name() { echo 'gdbm-1.12.tar.gz'; }
function tar_dir() { echo 'gdbm-1.12'; }

function config_pkg() {
    ./configure \
        --prefix=/usr \
        --disable-static \
        --enable-libgdbm-compat \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
