#!/bin/bash
function tar_name() { echo 'glibc-2.25.tar.xz'; }
function tar_dir() { echo 'glibc-2.25'; }

function config_pkg() {
    patch --forward --strip=1 --input=$SRC_DIR/glibc-2.25-fhs-1.patch
    ln -s ../lib/ld-linux-x86-64.so.2 /lib64 2> /dev/null
    ln -s ../lib/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3 2> /dev/null

    mkdir build && cd build \
    && ../configure \
             --prefix=/usr                \
             --enable-kernel=2.6.32          \
             --enable-obsolete-rpc           \
             --enable-stack-protector=strong \
             libc_cv_slibdir=/lib \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    # make check \
    # && return 0 || return 1
    return 0
}

function install_pkg() {
    touch /etc/ld.so.conf
    make install \
    && {
        cp ../nscd/nscd.conf /etc/nscd.conf
        mkdir -p /var/cache/nscd
        install -Dm644 ../nscd/nscd.tmpfiles /usr/lib/tmpfiles.d/nscd.conf
        install -Dm644 ../nscd/nscd.service /lib/systemd/system/nscd.service
        make localedata/install-locales

        # config Glibc
        echo "# Begin /etc/nsswitch.conf
passwd: files
group: files
shadow: files
hosts: files dns
networks: files
protocols: files
services: files
ethers: files
rpc: files
# End /etc/nsswitch.conf" > /etc/nsswitch.conf

        tar -xf $SRC_DIR/tzdata2016j.tar.gz
        ZONEINFO=/usr/share/zoneinfo
        mkdir -p $ZONEINFO/{posix,right}

        for tz in etcetera southamerica northamerica europe africa antarctica  \
                  asia australasia backward pacificnew systemv; do
            zic -L /dev/null   -d $ZONEINFO       -y "sh yearistype.sh" ${tz}
            zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz}
            zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz}
        done

        cp zone.tab zone1970.tab iso3166.tab $ZONEINFO
        zic -d $ZONEINFO -p Asia/Taipei
        unset ZONEINFO

        echo "# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib" > /etc/ld.so.conf

        # adjust the toolchain
        mv /tools/bin/{ld,ld-old}
        mv /tools/$(uname -m)-pc-linux-gnu/bin/{ld,ld-old}
        mv /tools/bin/{ld-new,ld}
        ln -s /tools/bin/ld /tools/$(uname -m)-pc-linux-gnu/bin/ld

        SPEC_PATH=`dirname $(gcc --print-libgcc-file-name)`/specs
        gcc -dumpspecs | sed -e 's@/tools@@g'                             \
            -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}'           \
            -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' > /tmp/gcc-specs \
        mount --bind /tmp/gcc-specs $SPEC_PATH
    } \
    && return 0 || return 1
}
