#!/bin/bash
function tar_name() { echo 'groff-1.22.3.tar.gz'; }
function tar_dir() { echo 'groff-1.22.3'; }

function config_pkg() {
    PAGE=<paper_size> ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
