#!/bin/bash
function tar_name() { echo 'gzip-1.8.tar.xz'; }
function tar_dir() { echo 'gzip-1.8'; }

function config_pkg() {
    ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && mv /usr/bin/gzip /bin \
    && return 0 || return 1
}
