#!/bin/bash
function tar_name() { echo 'iana-etc-2.30.tar.bz2'; }
function tar_dir() { echo 'iana-etc-2.30'; }

function config_pkg() {
    return 0
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
