#!/bin/bash
function tar_name() { echo 'kmod-23.tar.xz'; }
function tar_dir() { echo 'kmod-23'; }

function config_pkg() {
    ./configure \
        --prefix=/usr          \
        --bindir=/bin          \
        --sysconfdir=/etc      \
        --with-rootlibdir=/lib \
        --with-xz              \
        --with-zlib            \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && {
        for target in depmod insmod lsmod modinfo modprobe rmmod; do
            ln -sf ../bin/kmod /sbin/$target
        done
        ln -sf kmod /bin/lsmod
    } \
    && return 0 || return 1
}
