#!/bin/bash
function tar_name() { echo 'less-481.tar.gz'; }
function tar_dir() { echo 'less-481'; }

function config_pkg() {
    ./configure --prefix=/usr --sysconfdir=/etc \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
