#!/bin/bash
function tar_name() { echo 'libpipeline-1.4.1.tar.gz'; }
function tar_dir() { echo 'libpipeline-1.4.1'; }

function config_pkg() {
    PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
