#!/bin/bash
function tar_name() { echo 'make-4.2.1.tar.bz2'; }
function tar_dir() { echo 'make-4.2.1'; }

function config_pkg() {
    ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
