#!/bin/bash
function tar_name() { echo 'man-db-2.7.6.1.tar.xz'; }
function tar_dir() { echo 'man-db-2.7.6.1'; }

function config_pkg() {
    ./configure \
            --prefix=/usr                        \
            --docdir=/usr/share/doc/man-db-2.7.6.1 \
            --sysconfdir=/etc                    \
            --disable-setuid                     \
            --enable-cache-owner=bin             \
            --with-browser=/usr/bin/lynx         \
            --with-vgrind=/usr/bin/vgrind        \
            --with-grap=/usr/bin/grap \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && sed -i "s:man man:root root:g" /usr/lib/tmpfiles.d/man-db.conf \
    && return 0 || return 1
}
