#!/bin/bash
function tar_name() { echo 'mpc-1.0.3.tar.gz'; }
function tar_dir() { echo 'mpc-1.0.3'; }

function config_pkg() {
    ./configure --prefix=/usr    \
        --disable-static \
        --docdir=/usr/share/doc/mpc-1.0.3 \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && make html \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && make install-html \
    && return 0 || return 1
}
