#!/bin/bash
function tar_name() { echo 'pkg-config-0.29.1.tar.gz'; }
function tar_dir() { echo 'pkg-config-0.29.1'; }

function config_pkg() {
    ./configure \
        --prefix=/usr \
        --with-internal-glib       \
        --disable-compile-warnings \
        --disable-host-tool        \
        --docdir=/usr/share/doc/pkg-config-0.29.1 \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
