#!/bin/bash
function tar_name() { echo 'procps-ng-3.3.12.tar.xz'; }
function tar_dir() { echo 'procps-ng-3.3.12'; }

function config_pkg() {
    ./configure \
        --prefix=/usr                            \
        --exec-prefix=                           \
        --libdir=/usr/lib                        \
        --docdir=/usr/share/doc/procps-ng-3.3.12 \
        --disable-static                         \
        --disable-kill                           \
        --with-systemd \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    sed -i -r 's|(pmap_initname)\\\$|\1|' testsuite/pmap.test/pmap.exp \
    && make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && {
        mv /usr/lib/libprocps.so.* /lib
        ln -sf ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so
    } \
    && return 0 || return 1
}
