#!/bin/bash
function tar_name() { echo 'psmisc-22.21.tar.gz'; }
function tar_dir() { echo 'psmisc-22.21'; }

function config_pkg() {
    ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make install \
    && {
        mv /usr/bin/fuser   /bin
        mv /usr/bin/killall /bin
    } \
    && return 0 || return 1
}
