#!/bin/bash
function tar_name() { echo 'tar_name'; }
function tar_dir() { echo 'tar_dir'; }

function config_pkg() {
    sed -i '/MV.*old/d' Makefile.in \
    && sed -i '/{OLDSUFF}/c:' support/shlib-install \
    && ./configure \
        --prefix=/usr    \
        --disable-static \
        --docdir=/usr/share/doc/readline-7.0 \
    && return 0 || return 1
}

function make_pkg() {
    make SHLIB_LIBS=-lncurses -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make SHLIB_LIBS=-lncurses install \
    && {
        mv /usr/lib/lib{readline,history}.so.* /lib
        ln -sf ../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
        ln -sf ../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so
        install -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-7.0
    } \
    && return 0 || return 1
}
