#!/bin/bash
function tar_name() { echo 'sysklogd-1.5.1.tar.gz'; }
function tar_dir() { echo 'sysklogd-1.5.1'; }

function config_pkg() {
    sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c \
    && sed -i 's/union wait/int/' syslogd.c \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make BINDIR=/sbin install \
    && {
        # config Sysklogd
        echo "# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# End /etc/syslog.conf" > /etc/syslog.conf
    }
    && return 0 || return 1
}
