#!/bin/bash
function tar_name() { echo 'systemd-232.tar.xz'; }
function tar_dir() { echo 'systemd-232'; }

function config_pkg() {
    sed -i "s:blkid/::" $(grep -rl "blkid/blkid.h")
    sed -e 's@test/udev-test.pl @@' -e 's@test-copy$(EXEEXT) @@' -i Makefile.in
    echo "
KILL=/bin/kill
MOUNT_PATH=/bin/mount
UMOUNT_PATH=/bin/umount
HAVE_BLKID=1
BLKID_LIBS=-lblkid
BLKID_CFLAGS=-I/tools/include/blkid
HAVE_LIBMOUNT=1
MOUNT_LIBS=-lmount
MOUNT_CFLAGS=-I/tools/include/libmount
cc_cv_CFLAGS__flto=no
SULOGIN=/sbin/sulogin
XSLTPROC=/usr/bin/xsltproc" > config.cache
    ./configure \
        --prefix=/usr            \
        --sysconfdir=/etc        \
        --localstatedir=/var     \
        --config-cache           \
        --with-rootprefix=       \
        --with-rootlibdir=/lib   \
        --enable-split-usr       \
        --disable-firstboot      \
        --disable-ldconfig       \
        --disable-sysusers       \
        --without-python         \
        --with-default-dnssec=no \
        --docdir=/usr/share/doc/systemd-232 \
    && return 0 || return 1
}

function make_pkg() {
    make LIBRARY_PATH=/tools/lib -j8 \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make LD_LIBRARY_PATH=/tools/lib -j8 install \
    && {
        rm -rf /usr/lib/rpm
        for tool in runlevel reboot shutdown poweroff halt telinit; do
            ln -sf ../bin/systemctl /sbin/${tool}
        done
        ln -sf ../lib/systemd/systemd /sbin/init
        systemd-machine-id-setup
        sed -i "s:minix:ext4:g" src/test/test-path-util.c
    } \
    && make LD_LIBRARY_PATH=/tools/lib -k check \
    && return 0 || return 1
}
