#!/bin/bash
function tar_name() { echo 'sysvinit-2.88dsf.tar.bz2'; }
function tar_dir() { echo 'sysvinit-2.88dsf'; }

function config_pkg() {
    patch --forward --strip=1 --input=$SRC_DIR/sysvinit-2.88dsf-consolidated-1.patch \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 -C src \
    && return 0 || return 1
}

function check_pkg() {
    return 0
}

function install_pkg() {
    make -C src install \
    && return 0 || return 1
}
