#!/bin/bash
function tar_name() { echo 'tar-1.29.tar.xz'; }
function tar_dir() { echo 'tar-1.29'; }

function config_pkg() {
    FORCE_UNSAFE_CONFIGURE=1 \
    ./configure \
        --prefix=/usr \
        --bindir=/bin \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
    # return 0
}

function install_pkg() {
    make install \
    && make -C doc install-html docdir=/usr/share/doc/tar-1.29 \
    && return 0 || return 1
}
