#!/bin/bash
function tar_name() { echo 'texinfo-6.3.tar.xz'; }
function tar_dir() { echo 'texinfo-6.3'; }

function config_pkg() {
    ./configure --prefix=/usr --disable-static \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
