#!/bin/bash
function tar_name() { echo 'XML-Parser-2.44.tar.gz'; }
function tar_dir() { echo 'XML-Parser-2.44'; }

function config_pkg() {
    perl Makefile.PL \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make test \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
