#!/bin/bash
function tar_name() { echo 'zlib-1.2.11.tar.xz'; }
function tar_dir() { echo 'zlib-1.2.11'; }

function config_pkg() {
    ./configure --prefix=/usr \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
