#!/bin/bash
function tar_name() { echo 'tar_name'; }
function tar_dir() { echo 'tar_dir'; }

function config_pkg() {
    ./configure \
    && return 0 || return 1
}

function make_pkg() {
    make -j8 \
    && return 0 || return 1
}

function check_pkg() {
    make check \
    && return 0 || return 1
}

function install_pkg() {
    make install \
    && return 0 || return 1
}
